spring.application.name=Smart Healthcare Emergency Dispatcher
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/shed_db
spring.datasource.username=root
spring.datasource.password=Vikas@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
openroute.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImZlMzU5NmIzOTllZTQ5OWM5OTliZDc5MGQzM2NjYmUzIiwiaCI6Im11cm11cjY0In0=